### ISSUE TITLE
Error on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by dadoprom** [ducky64/labelmaker#3]
This error apreared on Ubuntu 14.04 (as well as on OSX with python3) working ok on ubuntu 16.04

python3 kp/kp-lepky-A4.svg kp/data1.csv test.svg
  File "kp/kp-lepky-A4.svg", line 1
    <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    ^
SyntaxError: invalid syntax

**Comment by ducky64** [comment]
I don't think you ran the correct command. The first argument passed to Python needs to be the script to be run (in this case, labelmaker.py), not the files to pass into the program.

**Comment by dadoprom** [comment]
sorry, stupid me :D

**Comment by dadoprom** [comment]
Ok, under OSX, python3 everything works as expected! All good, even diacritic marks... which is great.
