### ISSUE TITLE
bug: One label is missing

### ISSUE THREAD

**Issue by dadoprom** [ducky64/labelmaker#4]
labelmaker will not fill the entire page. One label is missing. I think it has to do something with the first line in cvs which contains the names of variables. So labels 8x3 should output 24 labels, but if so there is error saying "todo handle page overflow, new page support". With only 23 labels it is working ok, but one label is missing...

[navod.svg.zip](https://github.com/ducky64/labelmaker/files/266304/navod.svg.zip)

**Comment by ducky64** [comment]
Multipage support added, which should make this bug obsolete.

Note that with multipage support, it will no longer generate the output filename. If the output is specified as `output` or `output.svg`, it will instead generate `output_0.svg`, `output_1.svg`, and so on.

**Comment by dadoprom** [comment]
thank you, tested - working great! You should update the README file - multipage supported :)

**Comment by ducky64** [comment]
Good point, updated.
