### ISSUE TITLE
Feature request: position to start

### ISSUE THREAD

**Issue by dadoprom** [ducky64/labelmaker#5]
Now one last thing I would need. It often happens that you have a label sheet of paper where not all the labels were printed. Some are left empty. 

So is it possible to implement this:

Generate svg labels: position to start on row 2 column 2. But only for the first page. This would be optional feature, I mean if you have new sheet of labels (no missing labels) you do not have to specify the start position, it would generate the whole page or better said as many labels as requested. Something like this. See a attached example svg file. I hope you understand my english :D

[example-svg.zip](https://github.com/ducky64/labelmaker/files/270550/example-svg.zip)

**Comment by ducky64** [comment]
Implemented and documented (see updated usage section in readme)!

**Comment by dadoprom** [comment]
The start position is not working as expected. 

This is what is expected after this command:
python3 ../labelmaker.py kp-lepky-A4.svg univerzalna.csv  output/univ2.svg --start_row=2 --start_col=2
[univ-expected.zip](https://github.com/ducky64/labelmaker/files/273302/univ-expected.zip)

This is the output generated by the app after the above command:
[univ-output.zip](https://github.com/ducky64/labelmaker/files/273303/univ-output.zip)

**Comment by ducky64** [comment]
Now updated to specify label incrementing direction (`--dir`) as a command-line parameter rather than a template configuration. I think you will get the expected behavior with `--start_row=2 --start_col=0 --dir=row`

**Comment by dadoprom** [comment]
looking good, tested... if something I will report :) thank you, good work!
